name: Build & Release (Windows)

on:
  push:
    tags: ['v*']        # 推送形如 v1.0.0 / v20250822 的 tag 自动触发
  workflow_dispatch:     # 也支持手动触发
    inputs:
      version:
        description: '版本号（如 v20250822 或 v1.0.0；留空则用当天日期）'
        required: false

permissions:
  contents: write        # 允许创建 tag / 发布 release

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache: true

      - name: Compute VERSION
        run: |
          if ('${{ github.ref_type }}' -eq 'tag') {
            $v = '${{ github.ref_name }}'
          } elseif ('${{ inputs.version }}') {
            $v = '${{ inputs.version }}'
          } else {
            $v = 'v' + (Get-Date -Format yyyyMMdd)
          }
          "VERSION=$v" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          Write-Host "Release version: $v"

      - name: Verify embedded asset
        run: |
          if (-not (Test-Path '.\assets\7za.exe')) {
            Write-Error "assets\7za.exe 不存在。请把 7za.exe 放进仓库的 assets 目录（用于 go:embed）。"
          }

      - name: Build (Windows exe)
        run: |
          go build -ldflags "-s -w" -o auto_update.exe .

      - name: Package zip
        run: |
          $zip = "auto_update_$env:VERSION.zip"
          Compress-Archive -Path .\auto_update.exe, .\Register-AutoUpdate.ps1, .\Unregister-AutoUpdate.ps1 -DestinationPath $zip -Force
          "ZIP=$zip" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          Write-Host "Created $zip"

      # 手动触发时通常没有 tag，这里创建并推上去，确保 release 指向该 tag
      - name: Create tag if missing (manual dispatch)
        if: ${{ github.ref_type != 'tag' }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git tag $env:VERSION
          git push origin $env:VERSION

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: Auto Update ${{ env.VERSION }}
          files: ${{ env.ZIP }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
